# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  facetcher-build:

    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

# Invoke jobs via workflows
workflows:
  facetcher:
    jobs:
      - facetcher-build
